openapi: "3.0.0"
info:
  title: Shopping API
  version: "1.0"
paths: 
  /products:
    description: The products catalog
    get:
      summary: Search for products
      description: |
        Search for products in catalog
        using free query parameter
      parameters:
        - name: free-query
          description: |
            A product's name, reference, or
            partial description
          in: query
          required: false
          schema:
            type: string
      responses: 
        "200":
          description: |
            Products matching free query parameter
    post:
      summary: Add product
      description: |
        Add product (described in product info
        parameter) to catalog
      responses:
        "200":
          description: |
            Product added to catalog